export enum ErrorCode {
  // Generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  INVALID_INPUT = 'INVALID_INPUT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',

  // Order
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_ALREADY_ASSIGNED = 'ORDER_ALREADY_ASSIGNED',
  PARSE_FAILED = 'PARSE_FAILED',

  // Shipper
  SHIPPER_NOT_FOUND = 'SHIPPER_NOT_FOUND',
  SHIPPER_NOT_AVAILABLE = 'SHIPPER_NOT_AVAILABLE',
  NO_SHIPPER_NEARBY = 'NO_SHIPPER_NEARBY',

  // Webhook
  DUPLICATE_MESSAGE = 'DUPLICATE_MESSAGE',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
}
